<?php

/**
 * @param $talent - the name of the talent
 * @return string - the talents name in hungarian
 *
 * nuke this if you don't want it
 */

function get_hungarian_translation($talent) {
    switch ($talent) {
        case "Cursed Revolver": return "Átkozott Revolver";
        case "Godslayer": return "Istenölő";
        case "Defiant Fist": return "Gyanakvó Ököl";
        case "Battering Ram": return "Faltörő Kos";
        case "Slug Shot": return "Távollövés";
        case "Fortress Breaker": return "Erődtörő";
        case "Unstable Fissure": return "Instabil Időrés";
        case "Temporal Divide": return "Időosztás";
        case "Deja vu": return "Deja vu";
        case "Architectonics": return "Építészettan";
        case "Tinkerin": return "Bütykölés";
        case "Fortify": return "Megerősítés";
        case "Chain Reaction": return "Láncreakció";
        case "Royal Subjects": return "Királyi Alattvalók";
        case "Accelerant": return "Katalizátor";
        case "Ensnare": return "Hálócsapda";
        case "Bulk Up": return "Kigyúrt Felsőtest";
        case "Bounce House": return "Házrengető Földetérés";
        case "Exaction": return "Strapa";
        case "Impulse": return "Impulzus";
        case "Big Game": return "Nagy Játék";
        case "Dark Gifts": return "Sötét Ajándékok";
        case "Stunning Visage": return "Elkábító Ábrázat";
        case "Spreading Influence": return "Hatás Terjesztése";
        case "Scuttle": return "Szenesvödör";
        case "Hurl": return "Hajítás";
        case "Abyss Spike": return "Mélység-tüske";
        case "Combustible": return "Gyúlékony";
        case "Fusillade": return "Sortűz";
        case "W.Y.R.M. Jets": return "W.Y.R.M. Hajtómű";
        case "Over the Moon": return "A Hold Felett";
        case "Snow Globe": return "Hógömb";
        case "Wormhole": return "Féreglyuk";
        case "Aegis": return "Égisz";
        case "Scorch": return "Perzselés";
        case "Formidable": return "Félelmetesség";
        case "Cherish": return "Ápolás";
        case "Exterminate": return "Kiirtás";
        case "Solar Blessing": return "Napáldás";
        case "Totemic Ward": return "A Totem Őre";
        case "Spirit's Domain": return "Lelkek Tartománya";
        case "Maelstrom": return "Maelström";
        case "Rampant Blooming": return "Tomboló Virágzás";
        case "Ferocity": return "Vadság";
        case "Deep Roots": return "Mély Gyökerek";
        case "Splitting Ice": return "Szétváló Jég";
        case "Pyromania": return "Pirománia";
        case "Mana Rift": return "Manarés";
        case "Mother's Grace": return "Édesanya Kegyelme";
        case "Tremors": return "Remegés";
        case "Treacherous Ground": return "Áruló Talaj";
        case "Life Link": return "Életkapcsolat";
        case "Goddess' Blessing": return "Istennői Áldás";
        case "Sacrifice": return "Áldozat";
        case "Luminary": return "Égitest";
        case "Binary Star": return "Bináris Csillag";
        case "The Power Cosmeum": return "Az Égbolt Ereje";
        case "Lian's Shield": return "Lian Pajzsa";
        case "Storm of Bullets": return "Golyózápor";
        case "Vortex Grip": return "Örvényfogás";
        case "Steady Aim": return "Pontos Célzás";
        case "Reposition": return "Pozícióváltás";
        case "Eagle Eye": return "Sasszem";
        case "Adrenaline Junkie": return "Adrenalinfüggő";
        case "Blood Reaper": return "Vérgyilkos";
        case "Dragon Fangs": return "Sárkánykarmok";
        case "Discovery": return "Felfedezés";
        case "Heroism": return "Hősiesség";
        case "Death Hastens": return "Haláli Igyekezet";
        case "Alacrity": return "Vidámság";
        case "Eminence": return "Magaslat";
        case "Precision": return "Precizitás";
        case "Cat Burglar": return "Cicatolvaj";
        case "Street Justice": return "Utcai Igazságszolgáltatás";
        case "Rogue's Gambit": return "Zsivány Áldozata";
        case "Pluck": return "Bátorság";
        case "Half Shell": return "Félbúra";
        case "Leviathan": return "Leviatán";
        case "Spirit's Chosen": return "A Lélek Kiválasztottja";
        case "Ripened Gourd": return "Megérett Kulacs";
        case "Wekono's Wrath": return "Wekono Haragja";
        case "Snack Attack": return "Sütitámadás";
        case "Boom Boom": return "Bumm Bumm";
        case "Toot": return "Dudálás";
        case "Hell or High Water": return "Pokol vagy Magas Víz";
        case "Asymmetric Warfare": return "Aszimmetrikus Hadviselés";
        case "Display of Force": return "Az Erő Megjelenülése";
        case "Mega Potion": return "Mega Bájital";
        case "Catalyst": return "Reakcióindító";
        case "Combat Medic": return "Harci Orvos";
        case "Enforcer": return "Végrehajtó";
        case "Earthsplitter": return "Földhasító";
        case "Subservience": return "Engedelmesség";
        case "Flux Generator": return "Fluxgenerátor";
        case "Rocket Barrage": return "Rakétazápor";
        case "Aerial Assault": return "Légi Támadás";
        case "Soul Collector": return "Lélekgyűjtő";
        case "Mortal Reach": return "Halandó Távolság";
        case "Agony": return "Gyötrelem";
        case "Desert Silence": return "Sivatagi Csend";
        case "Recurve": return "Hátrahajlítás";
        case "Sand Trap": return "Homokcsapda";
        case "Debilitate": return "Gyengéd Tekintet";
        case "Smoke and Dagger": return "Füst és Tőrök";
        case "Preparation": return "Felkészültség";
        case "Nocturnal": return "Éjjeli Bagoly";
        case "Unauthorized Use": return "Jogtalan Használat";
        case "Crack Shot": return "Mesterlövész";
        case "Inner Strength": return "Belső Erő";
        case "Faustian Bargain": return "Fauszti Alku";
        case "Nothing Personal": return "Semmi Személyes";
        case "Undying": return "Halhatatlanság";
        case "Crush": return "Szétlapítás";
        case "Decimation": return "Tizedelés";
        case "Predatory Instincts": return "Ragadozói Ösztön";
        case "Tigron's Fury": return "Tigron Haragja";
        case "Vicious Assault": return "Vérszomjas Támadás";
        case "Thanks Grandpa": return "Köszönöm, Nagyapó";
        case "Direct Current": return "Egyenáram";
        case "Field Study": return "Terepmunka";
        case "Mercy Kill": return "Kegyelemdöfés";
        case "Hunting Party": return "Vadászcsoport";
        case "Burn Monster!": return "Égj, Szörnyeteg!";
        case "Omnipresence": return "Jelenvalóság";
        case "Unerring": return "Tévedhetetlen";
        case "Enveloping Shadow": return "Burkoló Árnyék";
        case "Cardio": return "Kardió";
        case "Burst Mode": return "Sorozatlövő-mód";
        case "Shrapnel": return "Repesz";
        case "Suspect Everyone": return "Gyanakodj Mindenkire!";
        case "Booby Trap": return "Kelepce";
        case "Opportunity in Chaos": return "Káosz Közepette Adódó Lehetőség";
        case "Unyielding Pressure": return "Hajthatatlan Nyomás";
        case "Relentless Presence": return "Könyörtelen Jelenlét";
        case "Deafening Silence": return "Süketítő Csend";
        case "Nightshade": return "Éjjeli Árny";
        case "Blastflower": return "Robbanóvirág";
        case "Scorn": return "Megvetés";
        case "Corrosive Acid": return "Maró Sav";
        case "Sight Begets Strength": return "A Látás Erőt Ad";
        case "Unnatural Persistence": return "Természetfeletti Kitartás";
        case "Focusing Lens": return "Fókuszáló Lencse";
        case "Life Exchange": return "Életváltás";
        case "Resonance": return "Rezonancia";
        case "Guillotine": return "Nyaktiló";
        case "Yomi": return "Yomi";
        case "Smolder": return "Parázslás";
        default: return "ezt nem tudom magyarul";
    }
}
